### ISSUE TITLE
How to compute TopHat 8 Mpc/h with this?

### ISSUE THREAD

**Issue by rainwoodman** [eelregit/mcfit#1]
Could you add an example computing TopHat sigma8 with a known power spectrum?
Thanks,

**Comment by eelregit** [comment]
Added to the docstring of cosmology.TophatVar. Hope it's clear enough.

**Comment by rainwoodman** [comment]
Thanks. It must be this commit.
https://github.com/eelregit/mcfit/commit/27fbb80de10c7076356420c3fcea184551c0db65

**Comment by rainwoodman** [comment]
@biweidai
