### ISSUE TITLE
From power spectrum to correlation function and vice-versa

### ISSUE THREAD

**Issue by MarcoMarinucci** [eelregit/mcfit#10]
Hello,

I'm a cosmologist and I'm following the basic examples that are provided in the README file to obtain the correlation function from a given power spectrum and vice-versa. I'm producing the linear PS with Class and inputting it into P2xi I found very weird results. Moreover, when I transform xi to PS using xi2P and then compare the result with the input PS I see deviations (oscillations basically) that are of order 5-15 %, too big for the accuracy  need. Is there a way to set the accuracy for the Fourier transform? I went through the code but wasn't able to spot it.
Thanks!

Marco

**Comment by eelregit** [comment]
As I mentioned in the email, can you try again with a much wider k range than (0.01, 1), say from 1e-4 to 1e2?
Because Hankel transform integrals are from 0 to infinity.

**Comment by MarcoMarinucci** [comment]
Changing the k-range to (1e-5, 1e2) solved the issue, the agreement in the range (1e-3,1e0) now is below 0.1 %.
Thanks.
