### ISSUE TITLE
nbodykit failure that seems to be related to mcfit.

### ISSUE THREAD

**Issue by rainwoodman** [eelregit/mcfit#3]
This failure seems to be related to how mcfit pad arrays:

https://travis-ci.org/bccp/nbodykit/jobs/394792659

**Comment by eelregit** [comment]
Update the mcfit in bccp conda channel to see if it is fixed?

**Comment by eelregit** [comment]
Seems it is.

**Comment by rainwoodman** [comment]
Yes it is fixed.
