### ISSUE TITLE
Question about how the y values are calculated

### ISSUE THREAD

**Issue by franlane94** [eelregit/mcfit#6]
Hi,

I was wondering whether you could give a brief description of the method used to calculate the y values that are returned when using the SphericalBessel transformation. Does it depend on the x values you input into the function? 

I had a look through the source code but couldn't quite figure out the process.

Thank you,

Fran Lane

**Comment by eelregit** [comment]
Hi Fran,

Yes and yes. The description is in the doc/mcfit.tex
https://github.com/eelregit/mcfit/blob/0ed0f4178d1065d949a040e9a8bf8bd045f1d476/doc/mcfit.tex#L115:L130

In brief, the current default simply takes the inverse.
And things are trickier if you pass `lowring=True`, and you need to read those equations.

For a longer explanation you can look at Sec B.5 of
https://arxiv.org/pdf/astro-ph/9905191.pdf

Please let me know if you have further questions.
Yin
