### ISSUE TITLE
Bug when l is odd for P2xi and xi2P

### ISSUE THREAD

**Issue by lhd23** [eelregit/mcfit#7]
Hello,

There seems to be a bug: when `l` is chosen odd `P2xi` returns a zero array. 
E.g. for the first spherical bessel function
```python
r, xi = P2xi(k, l=1)(P)
```
we get all zeros whereas
```python
r, xi1 = P2xi(k, l=0, deriv=1)(-P) # or
r, xi2 = SphericalBessel(k, nu=1)(P/(2.*pi)**1.5))
```
both produce the correct output (ignoring multiplication by i). This affects `xi2P` as well.

The issue is because you have multiplied by i^l and `np.fft.rfft` ignores the imaginary part, so computes FFT for a zero array.
Ideally for me there is a cosmology class that can evaluate xi^l_n (equation 18 in https://arxiv.org/abs/1603.04405). Then there would be no need to have to worry about the imaginary units.

Thanks for a great package.

**Comment by eelregit** [comment]
Thanks for pointing out the bug! Can you check if 662e519 fixes it before I publish a new version?

**Comment by eelregit** [comment]
Could you also give 44f5213 a try? The xi^l_n is added to P2xi.

**Comment by lhd23** [comment]
Thanks for the fixes. They work for me.
